# Generated by Django 5.2.7 on 2026-06-17 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_product_cost_price_suppliercosthistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='api.purchase'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='rounding',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
