# Generated by Django 5.2.7 on 2026-06-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_expense_purchase_purchase_rounding'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercosthistory',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
