# Generated by Django 5.2.7 on 2026-06-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_suppliercosthistory_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='deducted_credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
