# Generated by Django 6.0.6 on 2026-06-18 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_employee_basic_salary_employeesalarypayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='absent_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='half_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='month',
            field=models.CharField(default='2026-06', max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='employeeattendance',
            unique_together={('employee', 'month')},
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='present_days',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EmployeeAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Deducted', 'Deducted'), ('Reversed', 'Reversed')], default='Pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='api.employee')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_payment', to='api.expense')),
                ('paid_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.bankaccount')),
                ('salary_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deducted_advances', to='api.employeesalarypayment')),
            ],
        ),
        migrations.RemoveField(
            model_name='employeeattendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='employeeattendance',
            name='status',
        ),
    ]
