# Generated by Django 6.0.6 on 2026-06-18 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_employeeattendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='employeeattendance',
            unique_together={('employee', 'date')},
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Half Day', 'Half Day')], default='Present', max_length=20),
        ),
        migrations.RemoveField(
            model_name='employeeattendance',
            name='absent_days',
        ),
        migrations.RemoveField(
            model_name='employeeattendance',
            name='half_days',
        ),
        migrations.RemoveField(
            model_name='employeeattendance',
            name='month',
        ),
        migrations.RemoveField(
            model_name='employeeattendance',
            name='present_days',
        ),
    ]
