# Generated by Django 5.2.7 on 2026-06-18 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_employeeattendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='EmployeePayrollAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('salary_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='api.employeesalarypayment')),
            ],
        ),
    ]
