# Generated by Django 5.2.7 on 2026-06-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_employeeattendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
