# Generated by Django 5.2.7 on 2026-06-18 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_purchase_status_purchaseitem_returned_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTAUpdateBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Web asset version (e.g., 1.0.1)', max_length=32, unique=True)),
                ('native_version_required', models.CharField(help_text='Minimum native APK version required to run this bundle (e.g., 1.0.0)', max_length=32)),
                ('zip_file', models.FileField(help_text='ZIP file containing Vite build assets (index.html, assets/, etc.)', upload_to='ota_updates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])])),
                ('checksum', models.CharField(blank=True, editable=False, help_text='SHA-256 checksum generated automatically on save', max_length=64)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this update bundle is active and downloadable')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Forces the client app to apply the update immediately without confirmation')),
                ('release_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
