# Generated by Django 6.0.6 on 2026-06-22 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_otaupdatebundle_zip_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_models', to='api.brand')),
            ],
            options={
                'ordering': ['brand__name', 'model_name'],
                'unique_together': {('brand', 'model_name')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='suitable_models',
            field=models.ManyToManyField(blank=True, related_name='products', to='api.mobilemodel'),
        ),
    ]
