# Generated by Django 6.0.6 on 2026-06-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_mobilemodel_product_suitable_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='average_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
